# -*- coding: utf-8 -*-
"""sanjeevani_v2

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1uCvP2H2wWR5a0jQoSs-ITyWeE9bqnbhP
"""

#!pip install --upgrade gspread gspread-dataframe

import json
import os
import pandas as pd
import gspread
from gspread_dataframe import set_with_dataframe
from google.oauth2.service_account import Credentials

service_account_info = json.loads(os.environ["GCP_SERVICE_ACCOUNT"])

# Google Sheets Auth ----------
scopes = [
    "https://www.googleapis.com/auth/spreadsheets",
    "https://www.googleapis.com/auth/drive"
]

creds = Credentials.from_service_account_info(
    service_account_info,
    scopes=scopes
)

gc = gspread.authorize(creds)

# Open the existing spreadsheet by name. Make sure a file named 'Existing_Sheet_Name' exists in your Google Drive
sh = gc.open('demo_sanjeevani')

water = pd.read_csv("data/water.csv")
userData = pd.read_csv("data/userdata.csv")
steps = pd.read_csv("data/steps.csv")
spo2 = pd.read_csv("data/spo2.csv")
mSleep = pd.read_csv("data/msleep.csv")
heartRate = pd.read_csv("data/heartrate.csv")
game = pd.read_csv("data/games.csv")
food = pd.read_csv("data/food.csv")
dSleep = pd.read_csv("data/dsleep.csv")
appLaunch = pd.read_csv("data/applaunch.csv")
activity = pd.read_csv("data/activity.csv")
msg = pd.read_csv("data/msg.csv")
calls = pd.read_csv("data/calls.csv")
habits = pd.read_csv("data/habit.csv")

"""###user data"""

# 1. Select the worksheet (tab)
worksheet = sh.worksheet('sanjeevani user data') # get_worksheet for index

# 2. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 3. Paste the data
set_with_dataframe(worksheet, userData)

"""###steps"""

steps_pvt = steps.pivot_table(
    index='userId',
    columns='logDate',
    values='dayWiseSteps',
    aggfunc='sum'   # if multiple rows per user per date
    ).fillna(0).round(0).astype(int)

steps_pvt = steps_pvt[steps_pvt.columns[::-1]]
steps_pvt['total_steps'] = steps_pvt.sum(axis=1)
cols = ['total_steps'] + [c for c in steps_pvt.columns if c != 'total_steps']
steps_pvt = steps_pvt[cols]

steps_pvt.reset_index(inplace=True)

worksheet = sh.worksheet('steps') # get_worksheet for index
worksheet.clear()
set_with_dataframe(worksheet, steps_pvt)

"""###water"""

water_pvt = water.pivot_table(
    index='userId',
    columns='logDate',
    values='waterLogCount',
    aggfunc='sum'   # if multiple rows per user per date
    ).fillna(0).round(0).astype(int)
water_pvt.reset_index(inplace=True)

worksheet = sh.worksheet('water') # get_worksheet for index
worksheet.clear()
set_with_dataframe(worksheet, water_pvt)

"""###food"""

food_pvt = food.pivot_table(
    index='userId',
    columns='logDate',
    values='dailyFoodLogCount',
    aggfunc='sum'   # if multiple rows per user per date
    ).fillna(0).round(0).astype(int)
food_pvt.reset_index(inplace=True)

worksheet = sh.worksheet('food') # get_worksheet for index
worksheet.clear()
set_with_dataframe(worksheet, food_pvt)

"""###device sleep"""

dSleep_pvt = dSleep.pivot_table(
    index='userId',
    columns='logDate',
    values=['deviceSleepLogCount', 'deviceSleepDurationInMin'],
    aggfunc='sum'
).fillna(0).round(0).astype(int)

# Swap column MultiIndex levels
dSleep_pvt.columns = dSleep_pvt.columns.swaplevel(0, 1)


# Custom ordering for value names
desired_order = ['deviceSleepLogCount', 'deviceSleepDurationInMin']

# Reindex columns using MultiIndex sorting
dSleep_pvt = dSleep_pvt.reindex(
    columns=sorted(dSleep_pvt.columns, key=lambda x: (x[0], desired_order.index(x[1]))))
dSleep_pvt.reset_index(inplace=True)

worksheet = sh.worksheet('device sleep') # get_worksheet for index
worksheet.clear()
set_with_dataframe(worksheet, dSleep_pvt)

"""###manual sleep"""

mSleep_pvt = mSleep.pivot_table(
    index='userId',
    columns='logDate',
    values=['manualSleepLogCount', 'manualSleepDurationInMin'],
    aggfunc='sum'
).fillna(0).round(0).astype(int)

# Swap column MultiIndex levels
mSleep_pvt.columns = mSleep_pvt.columns.swaplevel(0, 1)

# Sort columns for clean ordering
#mSleep_pvt = mSleep_pvt.sort_index(axis=1)

# Custom ordering for value names
desired_order = ['manualSleepLogCount', 'manualSleepDurationInMin']

# Reindex columns using MultiIndex sorting
mSleep_pvt = mSleep_pvt.reindex(columns=sorted(mSleep_pvt.columns, key=lambda x: (x[0], desired_order.index(x[1]))))
mSleep_pvt.reset_index(inplace=True)

worksheet = sh.worksheet('manual sleep') # get_worksheet for index
worksheet.clear()
set_with_dataframe(worksheet, mSleep_pvt)

"""###activity"""

activity_pvt = activity.pivot_table(
    index='userId',
    columns='logDate',
    values=['activityLogCount','activityDurationInMin'],
    aggfunc='sum'
).fillna(0).round(0).astype(int)

# Swap column MultiIndex levels
activity_pvt.columns = activity_pvt.columns.swaplevel(0, 1)


# Custom ordering for value names
desired_order = ['activityLogCount','activityDurationInMin']

# Reindex columns using MultiIndex sorting
activity_pvt = activity_pvt.reindex(columns=sorted(activity_pvt.columns, key=lambda x: (x[0], desired_order.index(x[1]))))
activity_pvt.reset_index(inplace=True)

# 2. Select the worksheet (tab)
worksheet = sh.worksheet('activity') # get_worksheet for index

# 3. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 4. Paste the data
set_with_dataframe(worksheet, activity_pvt)

"""###SpO2"""

# Step 1: Create pivot with sum + mean
spo2_pvt = spo2.pivot_table(
    index='userid',
    columns='logDate',
    values='spo2Value',
    aggfunc=['mean', 'min' , 'max']
).fillna(0).round(1)

# Step 3: Flatten multi-index columns
spo2_pvt.columns = [f"{agg}_{date}" for agg, date in spo2_pvt.columns]

# Step 4: Reorder columns so sum_date and mean_date are adjacent
dates = sorted(spo2['logDate'].unique())
ordered_cols = []

for d in dates:
    ordered_cols.append(f"mean_{d}")
    ordered_cols.append(f"min_{d}")
    ordered_cols.append(f"max_{d}")

spo2_pvt = spo2_pvt[ordered_cols]
spo2_pvt.reset_index(inplace=True)

# 2. Select the worksheet (tab)
worksheet = sh.worksheet('SpO2') # get_worksheet for index

# 3. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 4. Paste the data
set_with_dataframe(worksheet, spo2_pvt)

"""###games"""

# game_pvt = game.pivot_table(
#     index='userid',
#     columns='logDate',
#     values=['gamename','cognitiveScore','gameScore'],
#     aggfunc={
#         'gamename': 'count',
#         'cognitiveScore': 'sum',
#         'gameScore': 'sum'
#     }
# ).fillna(0).round(0).astype(int)

# game_pvt.columns = game_pvt.columns.swaplevel(0, 1)

# desired_order = ['gamename','cognitiveScore', 'gameScore']

# game_pvt = game_pvt.reindex(
#     columns=sorted(game_pvt.columns, key=lambda x: (x[0], desired_order.index(x[1]))))
# game_pvt.reset_index(inplace=True)

# 2. Select the worksheet (tab)
worksheet = sh.worksheet('cognitive games details') # get_worksheet for index

# 3. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 4. Paste the data
set_with_dataframe(worksheet, game)

"""###heartrate"""

heartRate_pvt = heartRate.pivot_table(
    index='userid',
    columns='logDate',
    values=['lastRate', 'minRate', 'maxRate'],
    aggfunc={
        'lastRate': 'mean',
        'minRate': 'min',
        'maxRate': 'max'
    }
).fillna(0).round(0).astype(int)

# Rename functions for clarity
heartRate_pvt = heartRate_pvt.rename(columns={
    'lastRate': 'avg_of_lastRate',
    'minRate': 'min_of_minRate',
    'maxRate': 'max_of_maxRate'
})

# Swap levels so structure becomes date → metric
heartRate_pvt.columns = heartRate_pvt.columns.swaplevel(0, 1)

# Custom order of metrics
order = ['avg_of_lastRate', 'min_of_minRate', 'max_of_maxRate']

# Sort columns properly
heartRate_pvt = heartRate_pvt.reindex(
    columns=sorted(heartRate_pvt.columns, key=lambda x: (x[0], order.index(x[1])))
)
heartRate_pvt.reset_index(inplace=True)

# 2. Select the worksheet (tab)
worksheet = sh.worksheet('heart rate') # get_worksheet for index

# 3. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 4. Paste the data
set_with_dataframe(worksheet, heartRate_pvt )

"""###applaunch"""

appLaunch['appLaunchCount'] = 1
appLaunch_pvt = appLaunch.pivot_table(
    index='userId',
    columns='logDate',
    values='appLaunchCount',
    aggfunc='sum'   # if multiple rows per user per date
    ).fillna(0).round(0).astype(int)
appLaunch_pvt.reset_index(inplace=True)

# 2. Select the worksheet (tab)
worksheet = sh.worksheet('app launch') # get_worksheet for index

# 3. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 4. Paste the data
set_with_dataframe(worksheet, appLaunch_pvt)

"""###message"""

msg_pvt = msg.pivot_table(
    index='userId',
    columns='logDate',
    values=['userMsgCount','coachMsgCount','expertMsgCount'],
    aggfunc='sum'
).fillna(0).round(0).astype(int)

# Swap column MultiIndex levels
msg_pvt.columns = msg_pvt.columns.swaplevel(0, 1)


# Custom ordering for value names
desired_order = ['userMsgCount','coachMsgCount','expertMsgCount']

# Reindex columns using MultiIndex sorting
msg_pvt = msg_pvt.reindex(columns=sorted(msg_pvt.columns, key=lambda x: (x[0], desired_order.index(x[1]))))
msg_pvt.reset_index(inplace=True)

# 2. Select the worksheet (tab)
worksheet = sh.worksheet('msg') # get_worksheet for index

# 3. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 4. Paste the data
set_with_dataframe(worksheet, msg_pvt)

"""###calls"""

calls_pvt = calls.pivot_table(
    index='userId',
    columns='createdtime',
    values=['attemptedCallsCount','completedCallsCount'],
    aggfunc='sum'
).fillna(0).round(0).astype(int)

# Swap column MultiIndex levels
calls_pvt.columns = calls_pvt.columns.swaplevel(0, 1)


# Custom ordering for value names
desired_order = ['attemptedCallsCount','completedCallsCount']

# Reindex columns using MultiIndex sorting
calls_pvt = calls_pvt.reindex(
    columns=sorted(calls_pvt.columns, key=lambda x: (x[0], desired_order.index(x[1]))))
calls_pvt.reset_index(inplace=True)

# 2. Select the worksheet (tab)
worksheet = sh.worksheet('calls') # get_worksheet for index

# 3. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 4. Paste the data
set_with_dataframe(worksheet, calls_pvt)

"""###habit"""

# habits_pvt = habits.pivot_table(
#     index='userId',
#     columns='logDate',
#     values= 'habitTitle',
#     aggfunc='count'
# ).fillna(0).round(0).astype(int)
# habits_pvt.reset_index(inplace=True)

# 2. Select the worksheet (tab)
worksheet = sh.worksheet('habits details') # get_worksheet for index

# 3. Clear existing content (optional, to avoid appending data weirdly)
worksheet.clear()

# 4. Paste the data
set_with_dataframe(worksheet, habits)

"""###finish"""

print("Data successfully pasted!")